- name: Authenticate to GCP (WIF)
  uses: google-github-actions/auth@v2
  with:
    workload_identity_provider: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool24/providers/github-provider
    service_account: github-wif-sa@PROJECT_ID.iam.gserviceaccount.com